import { createHash, randomUUID } from "node:crypto";
import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import type { DatabaseClient } from "../db/client";
import type { AppConfig } from "../config/env";
import type { TaskPriority, TaskStatus, UserRole } from "../../../shared/types/domain";
import { getLanIPv4Addresses } from "../network";

type Db = any;
type User = { id: string; name: string; role: UserRole; isActive: boolean };
type Options = { config: AppConfig; database: DatabaseClient };
const SELECT_TASK = `SELECT t.id,t.title,t.description,t.priority,t.status,t.progress,t.due_date AS dueDate,t.owner_id AS ownerId,t.created_by AS createdBy,t.source,t.is_private AS isPrivate,t.created_at AS createdAt,t.updated_at AS updatedAt,t.completed_at AS completedAt,t.archived_at AS archivedAt,u.name AS ownerName,u.role AS ownerRole FROM tasks t LEFT JOIN users u ON u.id=t.owner_id`;

export async function registerWorkbenchRoutes(app: FastifyInstance, options: Options): Promise<void> {
  const db = options.database.getDatabase(); const cookie = options.config.sessionCookieName;
  const require = (request: FastifyRequest, reply: FastifyReply, _database: Db, _cookie: string): User | null => requireAuth(request, reply, db, cookie);
  app.post("/api/auth/access", async (request, reply) => { const token = String(((request.body ?? {}) as Record<string, unknown>).token ?? "").trim(); const user = token ? userByToken(db, token) : null; if (!user) return reply.code(401).send(fail("INVALID_TOKEN", "访问令牌无效")); const raw = session(db, user.id); reply.setCookie(cookie, raw, { httpOnly: true, sameSite: "lax", secure: request.protocol === "https", path: "/", maxAge: 2592000 }); return reply.send(ok({ user })); });
  app.post("/api/auth/logout", async (request, reply) => { const raw = request.cookies[cookie]; if (raw) run(db, "UPDATE access_sessions SET revoked_at=? WHERE session_hash=?", now(), hash(raw)); reply.clearCookie(cookie, { path: "/" }); return reply.send(ok(null)); });
  app.get("/api/auth/me", async (request, reply) => { const user = auth(request, db, cookie); if (!user) return reply.code(401).send(fail("UNAUTHENTICATED", "请先完成访问验证")); return reply.send(ok({ user })); });
  app.get("/api/access-info", async (request, reply) => { const user = requireOwner(request, reply, db, cookie); if (!user) return; const addresses = getLanIPv4Addresses(); return reply.send(ok({ port: options.config.port, host: options.config.host, localUrl: `http://127.0.0.1:${options.config.port}`, lanUrls: addresses.map((ip) => `http://${ip}:${options.config.port}`), warning: "仅将局域网地址发给同一网络内的助理，不要发送 127.0.0.1 或带令牌的链接" })); });

  app.get("/api/dashboard", async (request, reply) => { const user = require(request, reply, db, cookie); if (!user) return; notifyOverdueTasks(db); const tasks = visible(db, user, false); const todos = user.role === "owner" ? rows(db, "SELECT id,content,todo_date AS todoDate,is_completed AS isCompleted,completed_at AS completedAt,created_at AS createdAt,updated_at AS updatedAt FROM todos ORDER BY created_at DESC") : []; const notes = user.role === "owner" ? rows(db, "SELECT id,content,is_pinned AS isPinned,created_at AS createdAt,updated_at AS updatedAt FROM notes ORDER BY updated_at DESC") : []; return reply.send(ok({ user, tasks, todos, notes, stats: { tasks: tasks.length, activeTasks: tasks.filter((t: any) => t.status !== "completed").length, pendingTodos: todos.filter((t: any) => Number(t.isCompleted) === 0).length, notes: notes.length } })); });
  app.get("/api/tasks", async (request, reply) => { const user = require(request, reply, db, cookie); if (!user) return; notifyOverdueTasks(db); const q = (request.query ?? {}) as Record<string, unknown>; return reply.send(ok(visible(db, user, user.role === "owner" && q.includeArchived === "1", typeof q.status === "string" ? q.status : undefined, typeof q.assignee === "string" ? q.assignee : undefined))); });
  app.post("/api/tasks", async (request, reply) => { const user = require(request, reply, db, cookie); if (!user) return; if (user.role === "viewer") return reply.code(403).send(fail("FORBIDDEN", "查看者不能创建任务")); const b = (request.body ?? {}) as Record<string, unknown>; const title = String(b.title ?? "").trim(); if (!title) return reply.code(400).send(fail("VALIDATION_ERROR", "任务标题不能为空")); const ownerId = user.role === "assistant" ? user.id : ownerIdOf(b.ownerId, user.id); const owner = validateOwner(db, ownerId); if (!owner.valid) return reply.code(400).send(fail("VALIDATION_ERROR", owner.message)); const id = randomUUID(); const stamp = now(); run(db, "INSERT INTO tasks(id,title,description,priority,status,progress,due_date,owner_id,created_by,source,is_private,created_at,updated_at,completed_at,archived_at,wecom_fingerprint) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", id, title.slice(0, 240), String(b.description ?? ""), priority(b.priority), "todo", 0, date(b.dueDate), ownerId, user.id, user.role === "assistant" ? "assistant" : "manual", user.role === "owner" && b.isPrivate ? 1 : 0, stamp, stamp, null, null, null); event(db, id, user, "task_created", owner.user && owner.user.id !== user.id ? `创建并分配给 ${owner.user.name}` : "创建任务"); if (owner.user?.role === "assistant" && owner.user.id !== user.id) notify(db, [owner.user.id], user.id, id, "task_assigned", "收到新任务", `你收到来自 ${user.name} 的任务“${title}”`); return reply.code(201).send(ok(findTask(db, id))); });
  app.patch("/api/tasks/:id", async (request, reply) => { const user = requireOwner(request, reply, db, cookie); if (!user) return; const id = idOf(request); const current = findTask(db, id); if (!current) return reply.code(404).send(fail("NOT_FOUND", "任务不存在")); if (current.archivedAt) return reply.code(400).send(fail("ARCHIVED", "请先恢复归档任务")); const b = (request.body ?? {}) as Record<string, unknown>; if (b.progress !== undefined || b.status !== undefined) return reply.code(400).send(fail("FIELD_FORBIDDEN", "请使用进度和验收接口变更任务状态")); const title = String(b.title ?? current.title).trim(); if (!title) return reply.code(400).send(fail("VALIDATION_ERROR", "任务标题不能为空")); const ownerId = Object.prototype.hasOwnProperty.call(b, "ownerId") ? ownerIdOf(b.ownerId, null) : current.ownerId; const owner = validateOwner(db, ownerId); if (!owner.valid) return reply.code(400).send(fail("VALIDATION_ERROR", owner.message)); const isPrivate = b.isPrivate === undefined ? Number(current.isPrivate) : b.isPrivate ? 1 : 0; if (isPrivate && ownerId !== "owner") return reply.code(400).send(fail("VALIDATION_ERROR", "私密任务只能由主人负责")); const stamp = now(); run(db, "UPDATE tasks SET title=?,description=?,priority=?,due_date=?,owner_id=?,is_private=?,updated_at=? WHERE id=?", title.slice(0, 240), String(b.description ?? current.description), priority(b.priority ?? current.priority), b.dueDate === undefined ? current.dueDate : date(b.dueDate), ownerId, isPrivate, stamp, id); if (ownerId !== current.ownerId) { event(db, id, user, "task_reassigned", `负责人从 ${current.ownerName ?? "未分配"} 改为 ${owner.user?.name ?? "未分配"}`); notify(db, [current.ownerId, ownerId].filter((x): x is string => Boolean(x)), user.id, id, "task_reassigned", "任务负责人已变更", `任务“${current.title}”已重新分配`); } return reply.send(ok(findTask(db, id))); });
  app.post("/api/tasks/:id/progress", async (request, reply) => { const user = require(request, reply, db, cookie); if (!user) return; const id = idOf(request); const current = findTask(db, id); if (!current) return reply.code(404).send(fail("NOT_FOUND", "任务不存在")); if (current.archivedAt) return reply.code(400).send(fail("ARCHIVED", "请先恢复归档任务")); if (user.role === "viewer" || current.ownerId !== user.id) return reply.code(403).send(fail("FORBIDDEN", "只能更新自己负责的任务")); if (current.status === "pending_review") return reply.code(400).send(fail("INVALID_STATE", "任务已提交验收，请等待主人处理")); if (current.status === "completed") return reply.code(400).send(fail("INVALID_STATE", "已完成任务不能再更新进度")); const b = (request.body ?? {}) as Record<string, unknown>; const p = clamp(b.progress); const status: TaskStatus = user.role === "assistant" && p >= 100 ? "pending_review" : p >= 100 ? "completed" : p > 0 ? "in_progress" : "todo"; const stamp = now(); run(db, "UPDATE tasks SET progress=?,status=?,updated_at=?,completed_at=? WHERE id=?", p, status, stamp, status === "completed" ? (current.completedAt ?? stamp) : null, id); log(db, id, user, String(b.note ?? b.log ?? `进度更新为 ${p}%`).trim(), p); const updated = findTask(db, id); if (status === "pending_review") event(db, id, user, "task_submitted", "进度达到 100%，提交主人验收"); notifyParticipants(db, updated, user.id, status === "pending_review" ? "task_submitted" : "task_progress", status === "pending_review" ? "任务待验收" : "任务进度更新", `${user.name} 更新了任务“${updated.title}”`); return reply.send(ok(updated)); });
  app.post("/api/tasks/:id/submit-review", async (request, reply) => { const user = require(request, reply, db, cookie); if (!user) return; const id = idOf(request); const task = findTask(db, id); if (!task) return reply.code(404).send(fail("NOT_FOUND", "任务不存在")); if (task.archivedAt) return reply.code(400).send(fail("ARCHIVED", "请先恢复归档任务")); if (user.role !== "assistant" || task.ownerId !== user.id) return reply.code(403).send(fail("FORBIDDEN", "只有任务助理可以提交验收")); if (task.status === "pending_review") return reply.send(ok(task)); if (task.progress < 100) return reply.code(400).send(fail("VALIDATION_ERROR", "进度达到100%后才能提交验收")); run(db, "UPDATE tasks SET status='pending_review',updated_at=? WHERE id=?", now(), id); event(db, id, user, "task_submitted", String(((request.body ?? {}) as Record<string, unknown>).note ?? "提交主人验收")); const updated = findTask(db, id); notifyParticipants(db, updated, user.id, "task_submitted", "任务待验收", `任务“${updated.title}”等待主人验收`); return reply.send(ok(updated)); });
  app.post("/api/tasks/:id/approve", async (request, reply) => { const user = requireOwner(request, reply, db, cookie); if (!user) return; const id = idOf(request); const task = findTask(db, id); if (!task) return reply.code(404).send(fail("NOT_FOUND", "任务不存在")); if (task.archivedAt) return reply.code(400).send(fail("ARCHIVED", "请先恢复归档任务")); if (task.status !== "pending_review") return reply.code(400).send(fail("INVALID_STATE", "只有待验收任务可以通过")); const stamp = now(); run(db, "UPDATE tasks SET status='completed',progress=100,completed_at=?,updated_at=? WHERE id=?", stamp, stamp, id); event(db, id, user, "task_approved", String(((request.body ?? {}) as Record<string, unknown>).note ?? "主人验收通过")); const updated = findTask(db, id); notifyParticipants(db, updated, user.id, "task_approved", "任务验收通过", `任务“${updated.title}”已通过验收`); return reply.send(ok(updated)); });
  app.post("/api/tasks/:id/return", async (request, reply) => { const user = requireOwner(request, reply, db, cookie); if (!user) return; const id = idOf(request); const task = findTask(db, id); if (!task) return reply.code(404).send(fail("NOT_FOUND", "任务不存在")); if (task.archivedAt) return reply.code(400).send(fail("ARCHIVED", "请先恢复归档任务")); if (task.status !== "pending_review") return reply.code(400).send(fail("INVALID_STATE", "只有待验收任务可以退回")); const b = (request.body ?? {}) as Record<string, unknown>; const p = Math.min(task.progress, 99); const note = String(b.note ?? "主人退回任务，请继续处理").trim() || "主人退回任务，请继续处理"; run(db, "UPDATE tasks SET status='in_progress',progress=?,completed_at=NULL,updated_at=? WHERE id=?", p, now(), id); event(db, id, user, "task_returned", note); const updated = findTask(db, id); notifyParticipants(db, updated, user.id, "task_returned", "任务已退回", `任务“${updated.title}”已退回`); return reply.send(ok(updated)); });
  app.post("/api/tasks/:id/archive", async (request, reply) => { const user = requireOwner(request, reply, db, cookie); if (!user) return; const id = idOf(request); const task = findTask(db, id); if (!task) return reply.code(404).send(fail("NOT_FOUND", "任务不存在")); if (!task.archivedAt) { const stamp = now(); run(db, "UPDATE tasks SET archived_at=?,updated_at=? WHERE id=?", stamp, stamp, id); event(db, id, user, "task_archived", "任务已归档"); } return reply.send(ok(null)); });
  app.post("/api/tasks/:id/restore", async (request, reply) => { const user = requireOwner(request, reply, db, cookie); if (!user) return; const id = idOf(request); const task = findTask(db, id); if (!task) return reply.code(404).send(fail("NOT_FOUND", "任务不存在")); if (task.archivedAt) { run(db, "UPDATE tasks SET archived_at=NULL,updated_at=? WHERE id=?", now(), id); event(db, id, user, "task_restored", "任务已恢复"); } return reply.send(ok(findTask(db, id))); });
  app.delete("/api/tasks/:id", async (request, reply) => { const user = requireOwner(request, reply, db, cookie); if (!user) return; const id = idOf(request); const task = findTask(db, id); if (!task) return reply.code(404).send(fail("NOT_FOUND", "任务不存在")); if (!task.archivedAt) return reply.code(400).send(fail("ARCHIVE_REQUIRED", "请先归档任务，再彻底删除")); run(db, "DELETE FROM tasks WHERE id=?", id); return reply.send(ok(null)); });

  app.get("/api/tasks/:id/comments", async (request, reply) => { const user = require(request, reply, db, cookie); if (!user) return; const task = findTask(db, idOf(request)); if (!task) return reply.code(404).send(fail("NOT_FOUND", "任务不存在")); if (!canView(task, user)) return reply.code(403).send(fail("FORBIDDEN", "无权查看该任务")); return reply.send(ok(rows(db, "SELECT id,task_id AS taskId,author_id AS authorId,author_name AS authorName,author_role AS authorRole,content,created_at AS createdAt FROM task_comments WHERE task_id=? ORDER BY created_at", task.id))); });
  app.post("/api/tasks/:id/comments", async (request, reply) => { const user = require(request, reply, db, cookie); if (!user) return; const task = findTask(db, idOf(request)); if (!task) return reply.code(404).send(fail("NOT_FOUND", "任务不存在")); if (!canView(task, user)) return reply.code(403).send(fail("FORBIDDEN", "无权评论该任务")); const content = String(((request.body ?? {}) as Record<string, unknown>).content ?? ((request.body ?? {}) as Record<string, unknown>).text ?? "").trim(); if (!content) return reply.code(400).send(fail("VALIDATION_ERROR", "评论内容不能为空")); const stamp = now(); const comment = { id: randomUUID(), taskId: task.id, authorId: user.id, authorName: user.name, authorRole: user.role, content, createdAt: stamp }; run(db, "INSERT INTO task_comments(id,task_id,author_id,author_name,author_role,content,created_at) VALUES(?,?,?,?,?,?,?)", comment.id, task.id, user.id, user.name, user.role, content, stamp); notifyParticipants(db, task, user.id, "task_commented", "任务有新评论", `${user.name} 评论了任务“${task.title}”`); return reply.code(201).send(ok(comment)); });
  app.get("/api/tasks/:id/activity", async (request, reply) => { const user = require(request, reply, db, cookie); if (!user) return; const task = findTask(db, idOf(request)); if (!task) return reply.code(404).send(fail("NOT_FOUND", "任务不存在")); if (!canView(task, user)) return reply.code(403).send(fail("FORBIDDEN", "无权查看该任务")); const logs = rows(db, "SELECT id,'progress' AS kind,author_id AS authorId,author_name AS authorName,content,progress_snapshot AS progress,created_at AS createdAt FROM task_progress_logs WHERE task_id=?", task.id); const comments = rows(db, "SELECT id,'comment' AS kind,author_id AS authorId,author_name AS authorName,content,NULL AS progress,created_at AS createdAt FROM task_comments WHERE task_id=?", task.id); const events = rows(db, "SELECT id,event_type AS kind,actor_id AS authorId,actor_name AS authorName,content,NULL AS progress,created_at AS createdAt FROM task_events WHERE task_id=?", task.id); return reply.send(ok([...logs, ...comments, ...events].toSorted((a, b) => String(a.createdAt).localeCompare(String(b.createdAt))))); });

  app.get("/api/notifications", async (request, reply) => { const user = require(request, reply, db, cookie); if (!user) return; notifyOverdueTasks(db); const unread = (request.query as Record<string, unknown> | undefined)?.unread === "1"; return reply.send(ok(rows(db, `SELECT id,recipient_id AS recipientId,actor_id AS actorId,task_id AS taskId,report_id AS reportId,event_type AS eventType,title,message,is_read AS isRead,created_at AS createdAt,read_at AS readAt FROM notifications WHERE recipient_id=? ${unread ? "AND is_read=0" : ""} ORDER BY created_at DESC LIMIT 100`, user.id))); });
  app.post("/api/notifications/read", async (request, reply) => { const user = require(request, reply, db, cookie); if (!user) return; const b = (request.body ?? {}) as Record<string, unknown>; const stamp = now(); if (b.all) run(db, "UPDATE notifications SET is_read=1,read_at=? WHERE recipient_id=?", stamp, user.id); else if (typeof b.taskId === "string") run(db, "UPDATE notifications SET is_read=1,read_at=? WHERE recipient_id=? AND task_id=?", stamp, user.id, b.taskId); else if (Array.isArray(b.ids)) for (const id of b.ids) if (typeof id === "string") run(db, "UPDATE notifications SET is_read=1,read_at=? WHERE recipient_id=? AND id=?", stamp, user.id, id); return reply.send(ok(null)); });

  app.get("/api/users", async (request, reply) => { const user = requireOwner(request, reply, db, cookie); if (!user) return; return reply.send(ok(rows(db, "SELECT id,name,role,is_active AS isActive,created_at AS createdAt,updated_at AS updatedAt FROM users ORDER BY role,name"))); });
  app.post("/api/users", async (request, reply) => { const user = requireOwner(request, reply, db, cookie); if (!user) return; const b = (request.body ?? {}) as Record<string, unknown>; const name = String(b.name ?? "").trim(); const role = b.role === "assistant" || b.role === "viewer" ? b.role : null; if (!name || !role) return reply.code(400).send(fail("VALIDATION_ERROR", "请填写成员名称并选择角色")); const stamp = now(); const id = randomUUID(); const token = newToken(); run(db, "INSERT INTO users(id,name,role,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?)", id, name, role, 1, stamp, stamp); run(db, "INSERT INTO access_tokens(id,user_id,token_hash,created_at,expires_at,revoked_at) VALUES(?,?,?,?,NULL,NULL)", randomUUID(), id, hash(token), stamp); return reply.code(201).send(ok({ user: { id, name, role, isActive: true, createdAt: stamp, updatedAt: stamp }, token })); });
  app.patch("/api/users/:id", async (request, reply) => { const user = requireOwner(request, reply, db, cookie); if (!user) return; const id = idOf(request); if (id === "owner") return reply.code(400).send(fail("VALIDATION_ERROR", "不能停用主人账户")); const body = (request.body ?? {}) as Record<string, unknown>; if (typeof body.isActive !== "boolean") return reply.code(400).send(fail("VALIDATION_ERROR", "isActive 必须是布尔值")); const active = body.isActive; const result = run(db, "UPDATE users SET is_active=?,updated_at=? WHERE id=?", active ? 1 : 0, now(), id); if (!result.changes) return reply.code(404).send(fail("NOT_FOUND", "成员不存在")); if (!active) { run(db, "UPDATE access_sessions SET revoked_at=? WHERE user_id=?", now(), id); run(db, "UPDATE access_tokens SET revoked_at=? WHERE user_id=?", now(), id); } return reply.send(ok(null)); });
  app.post("/api/users/:id/token", async (request, reply) => { const user = requireOwner(request, reply, db, cookie); if (!user) return; const id = idOf(request); if (!one(db, "SELECT id FROM users WHERE id=? AND id<>?", id, "owner")) return reply.code(404).send(fail("NOT_FOUND", "成员不存在")); const token = newToken(); const stamp = now(); run(db, "UPDATE access_tokens SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL", stamp, id); run(db, "INSERT INTO access_tokens(id,user_id,token_hash,created_at,expires_at,revoked_at) VALUES(?,?,?,?,NULL,NULL)", randomUUID(), id, hash(token), stamp); return reply.send(ok({ token })); });

  app.get("/api/todos", async (request, reply) => { if (!requireOwner(request, reply, db, cookie)) return; return reply.send(ok(rows(db, "SELECT id,content,todo_date AS todoDate,is_completed AS isCompleted,completed_at AS completedAt,created_at AS createdAt,updated_at AS updatedAt FROM todos ORDER BY created_at DESC"))); });
  app.post("/api/todos", async (request, reply) => { if (!requireOwner(request, reply, db, cookie)) return; const b = (request.body ?? {}) as Record<string, unknown>; const content = String(b.content ?? "").trim(); if (!content) return reply.code(400).send(fail("VALIDATION_ERROR", "待办内容不能为空")); const stamp = now(); const id = randomUUID(); run(db, "INSERT INTO todos(id,content,todo_date,is_completed,completed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?)", id, content, date(b.todoDate), 0, null, stamp, stamp); return reply.code(201).send(ok(findTodo(db, id))); });
  app.patch("/api/todos/:id", async (request, reply) => { if (!requireOwner(request, reply, db, cookie)) return; const id = idOf(request); const c = findTodo(db, id); if (!c) return reply.code(404).send(fail("NOT_FOUND", "待办不存在")); const b = (request.body ?? {}) as Record<string, unknown>; const done = b.isCompleted === undefined ? Number(c.isCompleted) : b.isCompleted ? 1 : 0; const stamp = now(); run(db, "UPDATE todos SET content=?,todo_date=?,is_completed=?,completed_at=?,updated_at=? WHERE id=?", String(b.content ?? c.content), b.todoDate === undefined ? c.todoDate : date(b.todoDate), done, done ? (c.completedAt ?? stamp) : null, stamp, id); return reply.send(ok(findTodo(db, id))); });
  app.delete("/api/todos/:id", async (request, reply) => { if (!requireOwner(request, reply, db, cookie)) return; run(db, "DELETE FROM todos WHERE id=?", idOf(request)); return reply.send(ok(null)); });
  app.get("/api/notes", async (request, reply) => { if (!requireOwner(request, reply, db, cookie)) return; return reply.send(ok(rows(db, "SELECT id,content,is_pinned AS isPinned,created_at AS createdAt,updated_at AS updatedAt FROM notes ORDER BY updated_at DESC"))); });
  app.post("/api/notes", async (request, reply) => { if (!requireOwner(request, reply, db, cookie)) return; const content = String(((request.body ?? {}) as Record<string, unknown>).content ?? "").trim(); if (!content) return reply.code(400).send(fail("VALIDATION_ERROR", "笔记内容不能为空")); const stamp = now(); const id = randomUUID(); run(db, "INSERT INTO notes(id,content,is_pinned,created_at,updated_at) VALUES(?,?,?,?,?)", id, content, 0, stamp, stamp); return reply.code(201).send(ok(findNote(db, id))); });
  app.patch("/api/notes/:id", async (request, reply) => { if (!requireOwner(request, reply, db, cookie)) return; const id = idOf(request); const c = findNote(db, id); if (!c) return reply.code(404).send(fail("NOT_FOUND", "笔记不存在")); const b = (request.body ?? {}) as Record<string, unknown>; run(db, "UPDATE notes SET content=?,is_pinned=?,updated_at=? WHERE id=?", String(b.content ?? c.content), b.isPinned === undefined ? Number(c.isPinned) : b.isPinned ? 1 : 0, now(), id); return reply.send(ok(findNote(db, id))); });
  app.delete("/api/notes/:id", async (request, reply) => { if (!requireOwner(request, reply, db, cookie)) return; run(db, "DELETE FROM notes WHERE id=?", idOf(request)); return reply.send(ok(null)); });
  app.get("/api/files", async (request, reply) => { if (!requireOwner(request, reply, db, cookie)) return; const q = (request.query ?? {}) as Record<string, unknown>; const search = typeof q.search === "string" ? q.search.trim() : ""; const category = typeof q.category === "string" ? q.category.trim() : ""; const cond: string[] = []; const params: string[] = []; if (search) { cond.push("(name LIKE ? OR file_path LIKE ?)"); params.push(`%${search}%`, `%${search}%`); } if (category) { cond.push("category=?"); params.push(category); } return reply.send(ok(rows(db, `SELECT id,name,file_path AS filePath,category,last_used_at AS lastUsedAt,created_at AS createdAt,updated_at AS updatedAt FROM important_files ${cond.length ? `WHERE ${cond.join(" AND ")}` : ""} ORDER BY COALESCE(last_used_at,updated_at) DESC`, ...params))); });
  app.post("/api/files", async (request, reply) => { if (!requireOwner(request, reply, db, cookie)) return; const b = (request.body ?? {}) as Record<string, unknown>; const name = String(b.name ?? "").trim(); const filePath = String(b.filePath ?? "").trim(); if (!name || !filePath) return reply.code(400).send(fail("VALIDATION_ERROR", "文件名称和路径不能为空")); const stamp = now(); const id = randomUUID(); run(db, "INSERT INTO important_files(id,name,file_path,category,last_used_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?)", id, name, filePath, String(b.category ?? "").trim(), null, stamp, stamp); return reply.code(201).send(ok(findFile(db, id))); });
  app.post("/api/files/:id/use", async (request, reply) => { if (!requireOwner(request, reply, db, cookie)) return; const id = idOf(request); if (!findFile(db, id)) return reply.code(404).send(fail("NOT_FOUND", "文件不存在")); run(db, "UPDATE important_files SET last_used_at=?,updated_at=? WHERE id=?", now(), now(), id); return reply.send(ok(findFile(db, id))); });
  app.delete("/api/files/:id", async (request, reply) => { if (!requireOwner(request, reply, db, cookie)) return; run(db, "DELETE FROM important_files WHERE id=?", idOf(request)); return reply.send(ok(null)); });
  app.get("/api/review", async (request, reply) => { const user = requireOwner(request, reply, db, cookie); if (!user) return; const q = (request.query ?? {}) as Record<string, unknown>; const cond = ["t.archived_at IS NULL"]; const params: string[] = []; if (typeof q.from === "string") { cond.push("substr(t.updated_at,1,10)>=?"); params.push(q.from); } if (typeof q.to === "string") { cond.push("substr(t.updated_at,1,10)<=?"); params.push(q.to); } if (typeof q.ownerId === "string") { if (q.ownerId === "unassigned") cond.push("t.owner_id IS NULL"); else { cond.push("t.owner_id=?"); params.push(q.ownerId); } } if (typeof q.status === "string" && isStatus(q.status)) { cond.push("t.status=?"); params.push(q.status); } const tasks = rows(db, `${SELECT_TASK} WHERE ${cond.join(" AND ")} ORDER BY t.updated_at DESC`, ...params).map(task); const completed = tasks.filter((t: any) => t.status === "completed").length; const overdue = tasks.filter((t: any) => t.dueDate && t.dueDate < new Date().toISOString().slice(0, 10) && t.status !== "completed").length; return reply.send(ok({ tasks, summary: { total: tasks.length, completed, active: tasks.length - completed, overdue, completionRate: tasks.length ? Math.round(completed / tasks.length * 100) : 0 } })); });
  app.post("/api/inbox/preview", async (request, reply) => { const user = require(request, reply, db, cookie); if (!user) return; if (user.role === "viewer") return reply.code(403).send(fail("FORBIDDEN", "查看者不能导入任务")); const drafts = Array.isArray(((request.body ?? {}) as Record<string, unknown>).drafts) ? ((request.body as { drafts: Record<string, unknown>[] }).drafts) : []; return reply.send(ok(drafts.slice(0, 100).map((item) => { const title = String(item.title ?? "").trim(); const fingerprint = inboxFingerprint(item, title); return { ...item, title, fingerprint, duplicate: Boolean(title && one(db, "SELECT id FROM tasks WHERE wecom_fingerprint=?", fingerprint)) }; }))); });
  app.post("/api/inbox/import", async (request, reply) => { const user = require(request, reply, db, cookie); if (!user) return; if (user.role === "viewer") return reply.code(403).send(fail("FORBIDDEN", "查看者不能导入任务")); const b = (request.body ?? {}) as Record<string, unknown>; const drafts = Array.isArray(b.drafts) ? b.drafts : []; const created: TaskView[] = []; const skipped: Array<{ title: string; reason: string }> = []; const stamp = now(); for (const item of drafts.slice(0, 100) as Record<string, unknown>[]) { const title = String(item.title ?? "").trim(); if (!title) continue; const fp = inboxFingerprint(item, title); if (one(db, "SELECT id FROM tasks WHERE wecom_fingerprint=?", fp) && !b.allowDuplicates) { skipped.push({ title, reason: "疑似重复" }); continue; } const ownerId = user.role === "assistant" ? user.id : ownerIdOf(item.ownerId, null); const owner = validateOwner(db, ownerId); if (!owner.valid) { skipped.push({ title, reason: owner.message }); continue; } const id = randomUUID(); run(db, "INSERT INTO tasks(id,title,description,priority,status,progress,due_date,owner_id,created_by,source,is_private,created_at,updated_at,completed_at,archived_at,wecom_fingerprint) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", id, title.slice(0, 240), String(item.description ?? (item.sender ? `来自：${String(item.sender)}` : "")), priority(item.priority), "todo", 0, date(item.dueDate), ownerId, user.id, "wecom", 0, stamp, stamp, null, null, fp); event(db, id, user, "task_created", owner.user && owner.user.id !== user.id ? `从企微导入并分配给 ${owner.user.name}` : "从企微收件箱导入"); const t = findTask(db, id); if (t) created.push(t); if (owner.user?.role === "assistant" && owner.user.id !== user.id) notify(db, [owner.user.id], user.id, id, "task_assigned", "收到企微任务", `你收到企微任务“${title}”`); } return reply.code(201).send(ok({ created, skipped })); });
}

type TaskView = ReturnType<typeof task>;
function auth(request: FastifyRequest, db: Db, cookie: string): User | null { const raw = request.cookies[cookie]; if (!raw) return null; const row = one(db, "SELECT u.id,u.name,u.role,u.is_active AS isActive FROM access_sessions s JOIN users u ON u.id=s.user_id WHERE s.session_hash=? AND s.revoked_at IS NULL AND s.expires_at>? AND u.is_active=1", hash(raw), now()); return row ? toUser(row) : null; }
function requireAuth(request: FastifyRequest, reply: FastifyReply, db: Db, cookie: string): User | null { const user = auth(request, db, cookie); if (!user) { void reply.code(401).send(fail("UNAUTHENTICATED", "请先完成访问验证")); return null; } return user; }
function requireOwner(request: FastifyRequest, reply: FastifyReply, db: Db, cookie: string): User | null { const user = requireAuth(request, reply, db, cookie); if (!user) return null; if (user.role !== "owner") { void reply.code(403).send(fail("FORBIDDEN", "只有主人可以访问此功能")); return null; } return user; }
function userByToken(db: Db, token: string): User | null { const row = one(db, "SELECT u.id,u.name,u.role,u.is_active AS isActive FROM access_tokens a JOIN users u ON u.id=a.user_id WHERE a.token_hash=? AND a.revoked_at IS NULL AND (a.expires_at IS NULL OR a.expires_at>?) AND u.is_active=1", hash(token), now()); return row ? toUser(row) : null; }
function session(db: Db, userId: string): string { const raw = newToken(); run(db, "INSERT INTO access_sessions(id,user_id,session_hash,created_at,expires_at,revoked_at) VALUES(?,?,?,?,?,NULL)", randomUUID(), userId, hash(raw), now(), new Date(Date.now() + 2592000000).toISOString()); return raw; }
function visible(db: Db, user: User, includeArchived: boolean, status?: string, assignee?: string): TaskView[] { const all = rows(db, `${SELECT_TASK}${includeArchived ? "" : " WHERE t.archived_at IS NULL"} ORDER BY t.updated_at DESC`).map(task); return all.filter((t) => { if (!(user.role === "owner" || (user.role === "assistant" && t.ownerId === user.id) || (user.role === "viewer" && t.ownerRole === "assistant"))) return false; if (status && status !== "all" && t.status !== status) return false; if (assignee === "mine" && t.ownerId !== user.id) return false; if (assignee === "unassigned" && t.ownerId !== null) return false; if (assignee && assignee !== "mine" && assignee !== "unassigned" && assignee !== "all" && user.role === "owner" && t.ownerId !== assignee) return false; return true; }); }
function findTask(db: Db, id: string): TaskView | null { const row = one(db, `${SELECT_TASK} WHERE t.id=?`, id); return row ? task(row) : null; }
function canView(t: TaskView, user: User): boolean { return user.role === "owner" || (user.role === "assistant" && t.ownerId === user.id) || (user.role === "viewer" && t.ownerRole === "assistant"); }
function task(row: Record<string, unknown>): any { return { id: String(row.id), title: String(row.title), description: String(row.description ?? ""), priority: String(row.priority) as TaskPriority, status: String(row.status) as TaskStatus, progress: Number(row.progress), dueDate: row.dueDate == null ? null : String(row.dueDate), ownerId: row.ownerId == null ? null : String(row.ownerId), createdBy: String(row.createdBy), source: String(row.source), isPrivate: Number(row.isPrivate) === 1, createdAt: String(row.createdAt), updatedAt: String(row.updatedAt), completedAt: row.completedAt == null ? null : String(row.completedAt), archivedAt: row.archivedAt == null ? null : String(row.archivedAt), ownerName: row.ownerName == null ? undefined : String(row.ownerName), ownerRole: row.ownerRole == null ? undefined : String(row.ownerRole) as UserRole }; }
function validateOwner(db: Db, id: string | null): { valid: true; user?: User } | { valid: false; message: string } { if (id === null) return { valid: true }; const row = one(db, "SELECT id,name,role,is_active AS isActive FROM users WHERE id=?", id); if (!row) return { valid: false, message: "负责人不存在" }; const user = toUser(row); if (!user.isActive) return { valid: false, message: "负责人已停用" }; if (user.role !== "owner" && user.role !== "assistant") return { valid: false, message: "任务只能分配给主人或助理" }; return { valid: true, user }; }
function notify(db: Db, recipients: string[], actor: string, taskId: string | null, type: string, title: string, message: string): void { for (const recipient of [...new Set(recipients)].filter((x) => x !== actor)) run(db, "INSERT INTO notifications(id,recipient_id,actor_id,task_id,event_type,title,message,is_read,created_at,read_at) VALUES(?,?,?,?,?,?,?,?,?,NULL)", randomUUID(), recipient, actor, taskId, type, title, message, 0, now()); }
function notifyParticipants(db: Db, t: TaskView | null, actor: string, type: string, title: string, message: string): void { if (!t) return; notify(db, [t.ownerId, "owner"].filter((x): x is string => Boolean(x)), actor, t.id, type, title, message); }
function log(db: Db, taskId: string, user: User, content: string, progress: number | null): void { run(db, "INSERT INTO task_progress_logs(id,task_id,author_id,author_name,content,progress_snapshot,created_at) VALUES(?,?,?,?,?,?,?)", randomUUID(), taskId, user.id, user.name, content || "进度更新", progress, now()); }
function event(db: Db, taskId: string, user: User, type: "task_created" | "task_reassigned" | "task_submitted" | "task_approved" | "task_returned" | "task_archived" | "task_restored", content: string): void { run(db, "INSERT INTO task_events(id,task_id,actor_id,actor_name,event_type,content,created_at) VALUES(?,?,?,?,?,?,?)", randomUUID(), taskId, user.id, user.name, type, content, now()); }
function notifyOverdueTasks(db: Db): void { const today = new Date().toISOString().slice(0, 10); const overdue = rows(db, `${SELECT_TASK} WHERE t.archived_at IS NULL AND t.due_date IS NOT NULL AND t.due_date < ? AND t.status <> 'completed' AND t.overdue_notified_at IS NULL`, today).map(task) as TaskView[]; for (const item of overdue) { const recipients = [item.ownerId, "owner"].filter((value): value is string => Boolean(value)); for (const recipient of new Set(recipients)) run(db, "INSERT INTO notifications(id,recipient_id,actor_id,task_id,event_type,title,message,is_read,created_at,read_at) VALUES(?,?,NULL,?,?,?, ?,0,?,NULL)", randomUUID(), recipient, item.id, "task_overdue", "任务已逾期", `任务“${item.title}”已超过截止日期`, now()); run(db, "UPDATE tasks SET overdue_notified_at=? WHERE id=?", now(), item.id); } }
function findTodo(db: Db, id: string): any { return one(db, "SELECT id,content,todo_date AS todoDate,is_completed AS isCompleted,completed_at AS completedAt,created_at AS createdAt,updated_at AS updatedAt FROM todos WHERE id=?", id); }
function findNote(db: Db, id: string): any { return one(db, "SELECT id,content,is_pinned AS isPinned,created_at AS createdAt,updated_at AS updatedAt FROM notes WHERE id=?", id); }
function findFile(db: Db, id: string): any { return one(db, "SELECT id,name,file_path AS filePath,category,last_used_at AS lastUsedAt,created_at AS createdAt,updated_at AS updatedAt FROM important_files WHERE id=?", id); }
function toUser(row: Record<string, unknown>): User { return { id: String(row.id), name: String(row.name), role: String(row.role) as UserRole, isActive: Number(row.isActive ?? row.is_active) === 1 }; }
function ownerIdOf(value: unknown, fallback: string | null): string | null { return value === undefined || value === null || value === "" || value === "unassigned" ? (value === undefined ? fallback : null) : typeof value === "string" ? value : fallback; }
function inboxFingerprint(item: Record<string, unknown>, title: string): string { const supplied = typeof item.fingerprint === "string" ? item.fingerprint.trim() : ""; return supplied || hash(`${String(item.sender ?? "").trim()}\n${title}\n${String(item.messageAt ?? item.createdAt ?? item.dueDate ?? "").trim()}`); }
function priority(value: unknown): TaskPriority { return value === "P0" || value === "P2" ? value : "P1"; }
function isStatus(value: string): value is TaskStatus { return value === "todo" || value === "in_progress" || value === "pending_review" || value === "completed"; }
function clamp(value: unknown): number { const n = Number(value); return Number.isFinite(n) ? Math.max(0, Math.min(100, Math.round(n))) : 0; }
function date(value: unknown): string | null { return typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/u.test(value) ? value : null; }
function idOf(request: FastifyRequest): string { return String((request.params as { id: string }).id); }
function now(): string { return new Date().toISOString(); }
function newToken(): string { return randomUUID().replaceAll("-", "") + randomUUID().replaceAll("-", ""); }
function hash(value: string): string { return createHash("sha256").update(value).digest("hex"); }
function one(db: Db, sql: string, ...params: unknown[]): any { return db.prepare(sql).get(...params) ?? null; }
function rows(db: Db, sql: string, ...params: unknown[]): any[] { return db.prepare(sql).all(...params) as any[]; }
function run(db: Db, sql: string, ...params: unknown[]): any { return db.prepare(sql).run(...params); }
function ok<T>(data: T): { ok: true; data: T } { return { ok: true, data }; }
function fail(code: string, message: string): { ok: false; error: { code: string; message: string } } { return { ok: false, error: { code, message } }; }
